### ISSUE TITLE
Branch blacklist

### ISSUE THREAD

**Issue by ShonM** [janinko/ghprb#130]
Whitelist is great, but unfortunately is the inverse of what I'd like to be using. In my current project, all branches *except* a handful should be built. Those excluded are legacy branches for support of older systems that don't have tests

I'm no Java dev but, if given the time, I will definitely contribute code towards this

**Comment by gianarb** [comment]
Hello @ShonM did you have close this PR because did you try a solution?
Thanks

**Comment by ShonM** [comment]
I closed it because I didn't care to wait, and the solution I used was in the old branches I simply exit with code 0 to get a success. People handle it from there.

**Comment by gianarb** [comment]
Oh ok :) Thanks
