### ISSUE TITLE
Push local changes?

### ISSUE THREAD

**Issue by chrylis** [janinko/ghprb#179]
I have a project that depends on an upstream library that has its own pipeline. When I build my project from a PR, I'd like to be able to update the dependency version to the latest stable upstream. I have this working and committing to the local Git repository, but the PRB appears to use the GitHub API to merge and close the PR instead of pushing the local repository to upstream. Is there a way to configure that push, using Git Publisher or another method, that won't conflict with the PRB workflow?

**Comment by DavidTanner** [comment]
It sounds like you found the best path.  The plugin isn't actually doing anything with git, just github.
