### ISSUE TITLE
ENV variables need escaping

### ISSUE THREAD

**Issue by intel352** [janinko/ghprb#180]
Have an issue that is failing some builds, it appears that the ghprb ENV variables aren't being escaped.

```
[app_dc_ui] $ /var/lib/jenkins/tools/hudson.tasks.Ant_AntInstallation/ANT1.9.3/bin/ant -file build.xml -DghprbTargetBranch=dev/sprint10 -DghprbSourceBranch=feature/DWGL-2835-rox-searchresult-styling -DghprbPullId=1334 -Dsha1=origin/pr/1334/merge -DghprbPullLink=https://github.com/some/repo/pull/1334 -DghprbActualCommit=2e3e81c1622d1ab482be5b40c11a1e9a06e40572 -DWEBDAV_PASSWORD=**** '-DghprbPullTitle=DWGL-2835 Search Results - Styled the search result and "no result" page...' -DghprbPullAuthorEmail= "-DghprbPullDescription=GitHub pull request #1334 of commit 2e3e81c1622d1ab482be5b40c11a1e9a06e40572 automatically merged." -Dapp.cartridge=/var/lib/jenkins/jobs/some-repo/workspace/cartridges/app_dc_ui compile.sass
```

With error:

```
BUILD FAILED
Target "result page..." does not exist in the project "sass compilation with explicit inheritance".
```

Actually, I really don't follow why this is erroring, because for situations where the text has something like quotes or brackets, the overall variable entry is single-quoted, so I'd expect the result is not interpreted, yet somehow the cli still tries to interpret the value...

Am I misinterpreting that this is an escaping issue?

**Comment by DavidTanner** [comment]
The environment variables are passed to jenkins when the plugin requests a new build. I am not sure where you would want to look for your error.

**Comment by asgrim** [comment]
The problem in our system can be reproduced by creating a pull request on GitHub that contains double quotes (all PRs create builds on our Jenkins, so the build is auto triggered if that is any help). I have not tried with any other characters.

**Comment by intel352** [comment]
Agreed with @asgrim, this bug should not be simply closed out. The env variable(s) generated by ghprb aren't necessarily escaped correctly, thus causing errors when a PR with quotes is built.
