### ISSUE TITLE
Make pullrequest title and description is wrongly escaped in Jenkins

### ISSUE THREAD

**Issue by vorburger** [janinko/ghprb#184]
Using ghprb v1.14-7 on Jenkins ver. 1.577, in the left hand side "Build History" of a job I'm seeing:

```
Aug 28, 2014 12:21:11 PM
   <a title="UI configuration for MultiGeneratorsXtextBuilderParticipant (pair-programmed)"    
href="https://github.com/vorburger/com.temenos.ds.op/pull/2">PR #2</a>: UI configuration for MultiG...
```

as in it's displaying HTML source, escaped - instead if a clickabled link as you probably intended.

If this worked before, maybe some Jenkins API changed meanwhile and you have to tell it you're giving HTML so that it does not escape it? (I do NOT know Jenkins internals, just guessing from having dealt with similar problems in other systems in the past.)

I don't know if this has anything to do with https://github.com/janinko/ghprb/issues/144 ?

**Comment by jaor** [comment]
hi. i'm using jenkins 2.55 and ghprb 1.32 and i still have this issue... could it be something on my config? thanks!

**Comment by rakkatak** [comment]
I have the same issue still. I'm using Jenkins 2.11 and ghprb 1.38.0.

Can this be configured?

**Comment by atomarch** [comment]
Manage Jenkins > Configure Global Security.  Select "Safe HTML" as the Markup Formatter.
