### ISSUE TITLE
Trigger phrases do not work

### ISSUE THREAD

**Issue by tdiesler** [janinko/ghprb#188]
Jenkins: 1.578
ghprb: 1.15-1

Currently none of the trigger phrases seem to work. I cannot "ok to test", "add to whitelist", "retest this please"

To trigger a build I (as an admin) need to close and reopen a PR. For authors that are not part of the organisation I need to manually add them to the whitelist before

**Comment by skrobul** [comment]
why has this been closed? It's clearly not resolved. I have just run into exactly same problem - my GHE licenses are strictly limited and I simply don't have separate account to use just for jenkins, so I have to use my own.

**Comment by skrobul** [comment]
If anyone needs that functionality back, it looks like @akoeplinger broke this in 1fd29dee83ac7048b9a00088bed9e3b475c2ed68 which was first merged into `1.15-0`, so if you downgrade to `1.14-7` it works again.

**Comment by akoeplinger** [comment]
fwiw, this check was present in earlier versions of the plugin, I just merely added it back at the [request](https://github.com/jenkinsci/ghprb-plugin/pull/37#discussion-diff-15053615) of a maintainer cause it fixed a problem I was having in a much nicer way.

@skrobul I'm curious why you need the trigger phrases in a GitHub Enterprises environment, aren't your users trusted anyway?

**Comment by skrobul** [comment]
@akoeplinger  Thanks for clarification.

My users are trusted and this is not a problem. All of them are whitelisted. I need trigger phrases to restart build that failed. Almost all of  the users/admins can re-run the build by commenting 'retest this please'. Except me...because I was the one generating token for API access.
