### ISSUE TITLE
Skip Merge Commit Creation

### ISSUE THREAD

**Issue by teleshoes** [janinko/ghprb#196]
it would be nice to have the option to build the branch without merging first.

1) the git API assumes that the source branch commit is what is built; it puts a little checkmark next to the commit in question. however, it is possible for that commit to fail to build while the merge commit succeeds, and vice-versa.

2) it helps isolate failures to do BOTH ways. our previous build system built the branch without merging when the PR is created, and built the merge AFTER the PR was merged.

3) another immediately practical reason is to get useful buildnumbers in our deployed artifacts; the buildnumber displayed is the newly created merge commit. as this merge commit exists solely on the CI machine, its meaningless.

**Comment by DavidTanner** [comment]
The merge commit is actually created by github.  When you create a pull request github tries to merge the two branches,and gives you a green merge button if it can.   

If you want to only use the last commit to the pull request, then don't use the sha1 variable,  but use ghprbActualCommit

**Comment by larafields** [comment]
You should be aware that the merge commit has been deprecated by GitHub and is being removed from the API for exactly these kinds of problems.

**Comment by teleshoes** [comment]
ooh, thanks for the info!

**Comment by DavidTanner** [comment]
@larafields can you add a link to some documentation about that?  I am not seeing anything on the github blog about removing the merge commit.  If that is true then this plugin is going to stop working.

**Comment by DavidTanner** [comment]
@larafields You must be talking about the attribute you can get back from the API.  That was deprecated in 2013, but this plugin doesn't use it anyways.
https://developer.github.com/changes/2013-04-25-deprecating-merge-commit-sha/
