### ISSUE TITLE
Surface option to delete branch on Github when automatic merge is done

### ISSUE THREAD

**Issue by sgtcoolguy** [janinko/ghprb#198]
I can see in the code you have it written to delete the branch that was the source of the PR. I'd love to be able to turn that on, but it seems you've commented it out for now, without the ability to turn it on/off in a checkbox preference.

I'm assuming it's off because some users might want the branch kept around - or you may want to whitelist/blacklist branches to delete or keep using a regex? Obviously it'd be bad to wipe "master" off a fork because we accepted their PR and they didn't use a feature branch.

https://github.com/janinko/ghprb/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java#L168

**Comment by DavidTanner** [comment]
Actually i haven't looked into it for a while, but lay i checked i don't think the github plugin exposes that route.  It might take a pull request there first.
