### ISSUE TITLE
v1.16-1 - Cannot disable pull request comments

### ISSUE THREAD

**Issue by Dinoshauer** [janinko/ghprb#199]
Hey, since we upgraded to 1.16-1 we cannot get ghprb to stop commenting on PR's

![image](https://cloud.githubusercontent.com/assets/2325817/4558171/7c5ae1b8-4edc-11e4-8da1-7b54bb89e39e.png)

Jenkins settings regarding comments:

![image](https://cloud.githubusercontent.com/assets/2325817/4558179/9f302126-4edc-11e4-9597-aefb07e19655.png)

Jenkins ver. 1.583

**Comment by DavidTanner** [comment]
There was some of the code that got paved before the check for the published url. That should be fixed now.  

The build status icons are totally separate from the published url.
