### ISSUE TITLE
Build all commits inside a pull request

### ISSUE THREAD

**Issue by joeshaw** [janinko/ghprb#200]
Can a setting be added to build all commits added to a pull request rather than just the last one?  We generally like to test all the commits in a PR.

I looked through the settings and GitHub issues and couldn't find any way to do this.

**Comment by DavidTanner** [comment]
For your case why not just create a build that tests all commits using the regular source control triggers?

**Comment by joeshaw** [comment]
I think there's a misunderstanding. I want to build all the commits within a pull request, not just the latest commit. (bonus points for not rebuilding already built commits when the PR is updated)

I'm not sure how I can do this with regular build triggers without a plugin that understands pull requests.

**Comment by chiragverma28** [comment]
Is it still not resolved ? We are experiencing the same issue, where in our PR usually there are many commits but when the Job triggers only the most latest commit will execute. Using the below config:

refspec = +refs/pull/*:refs/remotes/origin/pr/*
branch specifier = ${sha1}
