### ISSUE TITLE
Pull meta data appearing in build history column

### ISSUE THREAD

**Issue by alexwhitman** [janinko/ghprb#204]
Using version 1.16-5 installed in Jenkins 1.580.1 (LTS branch) I'm getting pull request meta data appearing in the build history column of a job.  It's only there during the quiet period for the build.  The image below shows the type of meta data being shown.

![screenshot from 2014-11-03 14 43 23](https://cloud.githubusercontent.com/assets/422013/4884185/2b9c6728-6369-11e4-8d5f-6a4cd5ff0cf3.png)

**Comment by DavidTanner** [comment]
I don't believe the trigger has any control over this functionality.  If you can find a way to silence it, I will review and merge it.  

In the meantime I wouldn't really consider this a bug, more than just a nuisance.
