### ISSUE TITLE
Wrong hook URL in help text

### ISSUE THREAD

**Issue by Grandrath** [janinko/ghprb#206]
The help text for the checkbox "Use github hooks for build triggering" states:
```
...
If you want to create hook manualy set it for event types: issue_comment,	pull_request and url http://yourserver.com/jenkins/ghprbhook/.
...
```

When I used this hook URL it didn't work (resulted in 404). I had to change it to `http://example.com/ghprbhook/` (without the `/jenkins` path).

**Comment by DavidTanner** [comment]
When running a bitnami version on AWS, for example, the application is accessed with the /jenkins path.

**Comment by alexnauda** [comment]
This tripped me up, having installed Jenkins on Ubuntu using the default package. How are you measuring the popularity of the /jenkins context and/or the bitnami AMI?
