### ISSUE TITLE
Why does the job configuration of the plugin need to contain the name of the job?

### ISSUE THREAD

**Issue by dirk-thomas** [janinko/ghprb#210]
We are generating Jenkins jobs and were wondering why the configuration snippet of this plugin contains the job name:

    <org.jenkinsci.plugins.ghprb.GhprbTrigger plugin="ghprb@@1.16-5">
        ...
        <project>JOB_NAME</project>
    </org.jenkinsci.plugins.ghprb.GhprbTrigger>

Can't the plugin get the job name in a different way (rather then embedding it into the config snippet)?

**Comment by DavidTanner** [comment]
I am not sure why this is saved there. There is a project reference in Ghprb.java, and this may be jenkins way of saving a reference to it when it restarts/shuts down.
