### ISSUE TITLE
trigger phrases do not work if issued by the user who owns API key

### ISSUE THREAD

**Issue by skrobul** [janinko/ghprb#215]
This is continuation of closed #188. 

Despite not being best security practice, lot of people use their own Github accounts to generate API tokens. This is often due to limited number of accounts that organizations can create on GHE (licensing restrictions, etc). In my personal example, I used my own account to generate token for jenkins and it worked well for long time. 

Recently, I have updated GHPRB to newest release and it suddenly stopped working. After short investigation, it turns out that 1fd29de introduced breaking change by ignoring all comments from the bot user, therefore on-demand builds stopped working completely and to my knowledge there is no sensible workaround. Closing and re-opening PR is not sensible option.

For now, the only workaround I found was downgrading to `1.14-7`.

**Comment by DavidTanner** [comment]
You are right, at the time I didn't see anything wrong with it.  If you want to add a PR that adds an option to make this configurable I would be glad to review and release it.  It will take me a couple of days to get in there myself.

**Comment by akoeplinger** [comment]
Another option would be to check if the message equals the 'request for testing' phrase and skip it in that case. I originally implemented it this way, but was concerned about potential problems when text/character encoding or some other issues between GitHub <-> Jenkins prevent the string from being equal.

Given the issues the current solution causes this might be a better approach though, with the benefit of not needing yet another config option.

**Comment by DavidTanner** [comment]
In the branch I am adding for multiple github endpoints I also added a checkbox to ignore the bot user for each endpoint.
