### ISSUE TITLE
Customisable status

### ISSUE THREAD

**Issue by adrianmoisey** [janinko/ghprb#222]
Hi

It would be awesome the commit status was customisable. For example I want to use this plugin for tests, so I'd like to be able to say "Tests passed".

 https://github.com/janinko/ghprb/blob/5c06b3cec513b10e0ac735e4d48ea6cde1cc40a6/src/main/java/org/jenkinsci/plugins/ghprb/GhprbBuilds.java#L118

**Comment by NikolausDemmel** [comment]
+1

**Comment by bilke** [comment]
Yes this would be a nice feature! Maybe then it would also be possible to have several commit statuses from several jobs building the same pull request?!

**Comment by dhuebner** [comment]
+1
