### ISSUE TITLE
Test Phrase Environment Variable

### ISSUE THREAD

**Issue by jake-minted** [janinko/ghprb#223]
First of all :+1: for the awesome plugin! :100: 

Is there a way though to pass variables as a Jenkins Trigger Phrase?

E.g: I have several test suites available, and only need to test certain ones that apply to each PR. If I comment on the PR and say "Test $(suite1)", then I can run my test suite1. Same for suite2, etc.

I can configure my build script to do all of the regex and such, but I'm unsure if an environment variable is present for the "Trigger Phrase", or if the Trigger Phrase is a static match, such that I couldn't regex for a potential variable inside of the Trigger Phrase.

I could always create different jenkins test jobs for each suite with different Trigger Phrases, yet I figured this would be the easier option

Thanks again!

**Comment by NikolausDemmel** [comment]
This would be very useful to me too...
