### ISSUE TITLE
ghprbPullTitle is not updated

### ISSUE THREAD

**Issue by NikolausDemmel** [janinko/ghprb#230]
`ghprbPullTitle` is not updated when the title of the PR is updated and a retest is triggered.

It seems to remain at the intial value.

**Comment by DavidTanner** [comment]
Is this still the case with 1.17?

**Comment by eugeneiiim** [comment]
I'm seeing this as well. I'm using version 1.21.1.

**Comment by DavidTanner** [comment]
As far as I can tell everything is updating as it should.  I am using the latest though.  Look at the parameters for the build.  I just tried it locally, and the parameter was updated.  Are you using webhooks or the trigger?

**Comment by eugeneiiim** [comment]
It appears that the old title is still being passed in:
![image](https://cloud.githubusercontent.com/assets/31150/8147067/fea8100c-1211-11e5-8ed6-b2d6e39ce18c.png)

I'm triggering the build using "test this please" in the pull request UI. I'm using Github webhooks. My ghprb settings look like this:
![image](https://cloud.githubusercontent.com/assets/31150/8147064/b7dabf12-1211-11e5-8c64-92913d5843df.png)

**Comment by eugeneiiim** [comment]
A workaround we're using is to close and re-open the pull request after changing the title.

**Comment by DavidTanner** [comment]
Please check with 1.24.5
