### ISSUE TITLE
Checking X-Hub-Signature in POST header

### ISSUE THREAD

**Issue by Moliholy** [janinko/ghprb#233]
When creating a GitHub hook there is a possibility to share a secret (nothing but a string only known by Github and the actual user) to certify that the POST has been sent by GitHub. Every sent POST takes the Payload and the secret and creates a signature. That signature is included in the POST's header under the "X-Hub-Signature" field.

However this plugin only checks the content type and the "X-GitHub-Event" fields, completely ignoring the others.

Is it possible to check the signature? What are your ideas about the security issue in order to avoid unauthorized job executions?

**Comment by DavidTanner** [comment]
This functionality exists in the latest, 1.24.8
