### ISSUE TITLE
Deactivated Jobs should not trigger status updates

### ISSUE THREAD

**Issue by oehme** [janinko/ghprb#235]
I have several jobs running on our pull requests, each of which has its own commit status context.

However, there always is a context called "default" that points nowhere and which I cannot seem to get rid of. This is confusing to all contributors.

![default](https://cloud.githubusercontent.com/assets/1191797/6481711/1dc2989c-c260-11e4-99c5-9acba9efff14.PNG)

**Comment by oehme** [comment]
I found the reason: The "default" is caused by a deactivated build job. Deactivated jobs should not trigger any comments/status messages.

**Comment by DavidTanner** [comment]
Do you know of a way for the trigger to know that the job is not active?  You are welcome to enter a pull request and it will be reviewed.

**Comment by oehme** [comment]
Seems you found out already :) Thank you for looking into this!
Am 24.04.2015 06:22 schrieb "David Tanner" <notifications@github.com>:
