### ISSUE TITLE
how to customize PR comments by the bot ?

### ISSUE THREAD

**Issue by kajisaap** [janinko/ghprb#236]
Currently it always shows "Refer to this link for build results (access rights to CI server needed): " when i have this commenting feature turned on ? I could not find anyway to turn this off without turning off commenting feature or at least customize it ?

**Comment by DavidTanner** [comment]
I am working on a v2.0 branch that would make this configurable, but I don't have a ton of time to work on it usually.  It is almost ready for some alpha testing.

**Comment by DavidTanner** [comment]
Please check out 1.24.8 and see if it fits your needs

**Comment by kajisaap** [comment]
nice :bow:
