### ISSUE TITLE
Use a sane default context

### ISSUE THREAD

**Issue by 50Wliu** [janinko/ghprb#238]
Currently the "Commit Status Context" in advanced is left blank by default.  I'd be 100% fine with that except this leaves the context as Github as "default".  This isn't very helpful.  Could it instead be changed to something like `continuous-integration/jenkins/pr` (similar to how Travis does it)?

**Comment by 50Wliu** [comment]
Also, if you'd be willing to accept a PR for this, I could try...but no guarantees.  I have very limited experience with Java.

**Comment by DavidTanner** [comment]
I prefer the changes be made in the jenkins fork, but I don't know that it matters.  I think this makes sense and will release it with v1.18

**Comment by 50Wliu** [comment]
I don't care whether or not it's blank per-say, just that it has a saner default value.

**Comment by DavidTanner** [comment]
The default context is actually blank, and GitHub is the one that calls it default if you add another context.
