### ISSUE TITLE
Builder reports PR was automatically merged when it wasn't

### ISSUE THREAD

**Issue by rogthefrog** [janinko/ghprb#240]
When my PR builds and passes unit tests, the plugin always reports this:

----------------
xxx - AUTOMATED - # 21 GitHub pull request #285 of commit xxx automatically merged. 

even though 1) it does not actually merge and 2) I don't want it to merge automatically.

**Comment by DavidTanner** [comment]
The verbage is going to change in the next release to clarify this.  v1.18
