### ISSUE TITLE
After 'hpi:run', I couldn't see ghprb's UIs in Jenkins

### ISSUE THREAD

**Issue by Drdoteam** [janinko/ghprb#250]
Hi, I am looking into ghprb to add some functions.

So... first, I built master branch. And ghprb was on the installed plugins page(configure > plugins > ).
But, ghprb's UI is not showed in the global configure page and the job configure page.

I just clone ghprb master branch and mvn hpi:run.

It's my first time... so please comment!
I want to contribute to ghprb ~ 

This is my development environments.
* Windows
* Eclipse Juno
* m2e 1.4

**Comment by Drdoteam** [comment]
I find a solution. 
I imported the ghprb and run it in eclipse m2e.
So, it didn't work.

Then, I run it in cmd and it works well. I could see the ghprb's UIs.
Thank you! 

I read this article.
https://wiki.jenkins-ci.org/display/JENKINS/Plugin+tutorial

**Comment by DavidTanner** [comment]
I was just struggling with this issue last week.  I had done the same thing by accidentally importing it as a maven project.  Thanks for the pointers!
