### ISSUE TITLE
NullPointerException in GhprbTrigger.run()

### ISSUE THREAD

**Issue by AngledLuffa** [janinko/ghprb#256]
I'm getting the following null pointer exception when running Ghprb from a private repository.  I'm using Jenkins 1.610, GHPRB 1.17, Github plugin 1.11.3, Github API Plugin 1.16.1, GIT plugin 2.3.5, and GIT client plugin 1.16.1.  All are current AFAIK.

We currently have "auto-manage hook URLs" set, and "Test Credential" returns "Verified".

When I "Test Service" on the github hook page, the request shows up in the jenkins log.

Please let us know if there is any further information I can give for solving this issue.  Thanks!

org.jenkinsci.plugins.ghprb.GhprbTrigger.run() failed for hudson.model.FreeStyleProject@6d6a640e[pull_requests]
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:149)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:265)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:214)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by DavidTanner** [comment]
As far as I can tell that line will only be null if the trigger was stopped, and never started.  Please make sure that the version you are using matches what you reported here.

**Comment by AngledLuffa** [comment]
There is the following line in the system log when Jenkins starts, not sure if it is relevant or not:

Failed to instantiate optional component com.cloudbees.jenkins.GitHubRepositoryNameContributor$FromMultiSCM; skipping

The Github API Plugin is 1.67, I miswrote that earlier.  The other versions are as written.

Is there any further information I can give to help diagnose the issue?

Thanks for your help!

**Comment by AngledLuffa** [comment]
I updated to version 1.20.  The exception is now occurring in GhprbTrigger:155, at the line

`if (helper.isProjectDisabled())`

Also, at startup the following error is in the logs:

`GitHub project not set up, cannot start ghprb trigger for job ...`

I will continue to investigate to see why this is happening.  As far as I know, we followed the setup instructions correctly.

**Comment by AngledLuffa** [comment]
... maybe we're idiots who didn't notice that the github url needs to be entered in two places, not just one.  It's building one of our pull requests now.

A couple friendly logging suggestions, line numbers relative to the code from release 1.20:

at line 155 insert a copy of the block

```
        if (helper == null) {
            logger.log(Level.SEVERE, "The ghprb trigger for {0} wasn''t properly started - helper is null", this.project);
            return null;
        }
```

Change line 118 to

```
            logger.log(Level.INFO, "GitHub project not set up, cannot start ghprb trigger for job " + this.project + ".  Did you forget to enter the GitHub project URL?");
```

Thanks!
