### ISSUE TITLE
PR builder is building one commit behind

### ISSUE THREAD

**Issue by kmarquardsen** [janinko/ghprb#257]
It appears to not actually be treating the PR as if it's merged. Has anyone seen this before?

**Comment by sttts** [comment]
Same here.

**Comment by larafields** [comment]
We were seeing the same thing, and tracked it down to a timing issue - see details and a workaround here to see if it matches what you are seeing: https://github.com/janinko/ghprb/issues/269

**Comment by DavidTanner** [comment]
Use the Quiet period advanced setting to put a pause between builds for GitHub to catch up.

**Comment by larafields** [comment]
The quiet period ONLY works when the build is initially triggered. If a build is running when the second build is triggered, the quiet period runs and is expired by the time the first build completes. The second build then starts immediately.

**Comment by larafields** [comment]
Having said that, there is a plugin that will run commands in any build prior to the SCM fetch. Installing that plugin and then running a 5 second sleep is sufficient.
