### ISSUE TITLE
"Only merge on trigger phrase" does not work

### ISSUE THREAD

**Issue by highlyunavailable** [janinko/ghprb#264]
Plugin version: 1.20 Jenkins version: 1.611

This is regarding the "GitHub Pull Request Merger" post-build action.

There is no place to set the trigger phrase, and there is nothing in the docs about what the correct phrase is, though "ok to merge" shows up in a test file, though does not cause a merge.

Checking it causes the following message in the PR comments:
Please comment with '' to automerge this request

This also causes the build to fail with the following error:
```
The comment does not contain the required trigger phrase.

Finished: FAILURE
```

Logs:

```
May 12, 2015 12:36:16 AM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Got payload event: pull_request
May 12, 2015 12:36:16 AM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Checking PR #63 for redacted/myrepo
May 12, 2015 12:36:16 AM FINE org.jenkinsci.plugins.ghprb.GhprbGitHub
org.hasMember(member)? user:highlyunavailable org: redacted == yes
May 12, 2015 12:36:16 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest 
Created Pull Request #63 on redacted/myrepo by highlyunavailable () updated at: 5/12/15 12:36 AM SHA: ca926bc72fe2e5550ed5b6057ae88b4923922cf6
May 12, 2015 12:36:16 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running the build
May 12, 2015 12:36:16 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
PR is not null, checking if mergable
May 12, 2015 12:36:16 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running build...
May 12, 2015 12:36:16 AM INFO org.jenkinsci.plugins.ghprb.GhprbRepository createCommitStatus
Setting status of ca926bc72fe2e5550ed5b6057ae88b4923922cf6 to PENDING with url null and message:  Build triggered. sha1 is merged.
May 12, 2015 12:36:16 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest build
 Build triggered. sha1 is merged.
May 12, 2015 12:36:28 AM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Got payload event: issue_comment
May 12, 2015 12:36:28 AM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Checking issue comment 'org.kohsuke.github.GHIssueComment@1ada620' for repo redacted/myrepo
May 12, 2015 12:36:28 AM FINER org.jenkinsci.plugins.ghprb.GhprbRepository
Comment on issue #63 from User:redactedJenkinsBot: Please comment with '' to automerge this request
May 12, 2015 12:36:28 AM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Got payload event: issue_comment
May 12, 2015 12:36:28 AM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Checking issue comment 'org.kohsuke.github.GHIssueComment@223cfd' for repo redacted/myrepo
May 12, 2015 12:36:28 AM FINER org.jenkinsci.plugins.ghprb.GhprbRepository
Comment on issue #63 from User:redactedJenkinsBot: 
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.redacted.com//job/Git%20PR/11/
Test FAILed.
```

**Comment by DavidTanner** [comment]
The trigger phrase is set as part of the trigger.  It is not a regular expression, so it has to match exaclty.  I am looking to change the ui so the merge isn't a post build step, but an extension to the trigger to avoid this kind of confusion.

**Comment by highlyunavailable** [comment]
Then where do you set the trigger phrase? Matching exactly is fine, but it seems to me that the message in the GH PR log `Please comment with '' to automerge this request` which maps to https://github.com/janinko/ghprb/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java#L144 seems to indicate that the trigger phrase is empty, which means it can't be merged using a trigger phrase.

I'm trying to support the functionality where we get a PR. Everyone internally is an admin, but we still want a "LGTM" signoff on a merge post-code review. Since all admins are auto-whitelisted due to how this plugin's logic works, we have to have a merge trigger phrase, but there is no place to set it and there seems to be no default one.

**Comment by highlyunavailable** [comment]
Ah, it's the "Trigger phrase" section of the config, isn't it? I thought that was just a default-overrider that would be used if you wanted a build-specific trigger rather than "ok to test".

**Comment by DavidTanner** [comment]
You got it.  Sorry for the confusion.

**Comment by kratsg** [comment]
Hi,

I'm running into this issue as well. It's not clear where the "ok to merge" phrase is?
