### ISSUE TITLE
Updating github key apparently requires a jenkins restart

### ISSUE THREAD

**Issue by AngledLuffa** [janinko/ghprb#267]
We originally set up our ghprb using one of the engineer's github key.  Once we got it working, we created a new, dedicated user for our continuous integration and used its keys instead.

When we updated `access token` under `GitHub pull request builder` in `Configure System`, ghprb continued to post github comments as <engineer> until we restarted Jenkins.

**Comment by DavidTanner** [comment]
This is something I will look into with multiple github end points.  The plugin is creating an instance of the connection, then never letting it go.  It should only get it when it is needed.

**Comment by DavidTanner** [comment]
Fixed with version 1.24, use 1.24.8 or later.
