### ISSUE TITLE
Comments on the PR trigger jenkins but jenkins does not trigger github

### ISSUE THREAD

**Issue by Nek-** [janinko/ghprb#271]
Hello,

I notice a weird behavior when you trigger builds manually. (in my project, we don't want jenkins build automatically every PR because it takes a lot of time)

When you create a pull-request on the github, then you add the comment to trigger jenkins, everything is ok. The build start and jenkins tell github about the current status of the build. As you can see on this screenshot: 

![screen_jenkins_success](https://cloud.githubusercontent.com/assets/972456/7814720/3dbd2e78-03c4-11e5-9fce-8878534ed9e5.png)

After added a commit, then when you try to start again a build, the build is started by jenkins but github does not receive information about the build. Checkout the following screenshot:

![screen_jenkins_fail](https://cloud.githubusercontent.com/assets/972456/7814765/8ba6ef98-03c4-11e5-85fd-c954ed5c4dba.png)

I have no idea where comes this bug, or how to fix it. But i tried many configurations of the plugin and nothing to do, the problem is still here.

Don't hesitate to ask anything if i'm not clear enough.

**Comment by KostyaSha** [comment]
Please don't highlight unrelated repo. Thanks.
