### ISSUE TITLE
org.jenkinsci.plugins.ghprb.extensions.GhprbCommitStatusException

### ISSUE THREAD

**Issue by nykolaslima** [janinko/ghprb#278]
I'm getting this exception when the build starts and when it finishes.

`org.jenkinsci.plugins.ghprb.extensions.GhprbCommitStatusException`

My build is finishing with success but the PR status keep as "running": `Waiting to hear about 1111a1a — Build triggered. sha1 is merged.`

How can I fix it?

**Comment by obuckley-kenzan** [comment]
I am seeing this as well!

**Comment by obuckley-kenzan** [comment]
I got this working!  I had a few issues I hard worked out, but eventually I was able to get it working using a few of the references here, and some notes

1) Make sure you include the path to your repo in the Github Project field at the top of your job config page
2) Make sure you generate an access token for an Admin user in the Global PR Builder config
3) Make sure you only use the PR Builder, not in conjunction with any other polling / SCM plugins
4) Make sure access token has repo enabled
5) I used ${sha1} as the branch specifier
6) My github account is an organization, so I whitelisted my organization

References
* http://kabisa.nl/en/building-github-pull-requests-with-jenkins/
* http://brknthmb.com/post/75173073594/jenkins-using-the-github-pull-request-builder
* http://stackoverflow.com/questions/20137528/jenkins-github-pull-request-builder-plugin-is-not-posting-to-github/20152228#20152228
* https://github.com/janinko/ghprb/issues/12

**Comment by DavidTanner** [comment]
I am sorry about that.  The context wasn't set to null || "some text" properly, causing the commit status code to crash.  It is fixed in 1.22.1, but get 1.22.2 when it gets to the update center today.  

If you want to fix it now though, set the context in each job to "default" or some other context.
