### ISSUE TITLE
"Connect to API" is not working

### ISSUE THREAD

**Issue by sgykfjsm** [janinko/ghprb#287]
When I clicked "Connect to API" button, this messages is displayed
```
HTTP ERROR 404

Problem accessing /descriptorByName/org.jenkinsci.plugins.ghprb.GhprbGitHubAuth/connectToAPI. Reason:

    Not Found
Powered by Jetty://
```
My environment is:
- java version "1.7.0_79"
- Jenkins ver. 1.615
- GitHub Pull Request Builder 1.23.2

**Comment by mskutin** [comment]
Absolutely the same behaviour.

Env:
* jdk_1.8.0_20-b26
* Jenkins 1.616
* GitHub Pull Request Builder 1.23.2

**Comment by DavidTanner** [comment]
Sorry, I didn't add the method,  I will get it updated and out this morning.

**Comment by DavidTanner** [comment]
1.23.3 has been released.
