### ISSUE TITLE
Comments not being added to pull request on job completion

### ISSUE THREAD

**Issue by robertfalconer** [janinko/ghprb#293]
I have ghprb set up and mostly working with jenkins, the only part that doesn't seem to work is the posting of a _Test PASSed_ or _Test FAILed_ comment on the pull request. I can create a pull request, and ghprb automatically triggers the jenkins build, updates the commit status and merge warning message, and runs. When the job completes the commit status and merge warnings update to either the failed or success states as appropriate, but there is never pull request comment added.

I seem to have all the information in place, the github repo url, web hook credentials and the login details of a user that should be posting the comment. This is most likely a misconfiguration of my jenkins server, but I was hoping to get some information about how the plugin changes PR statuses and post comments, and the difference between the process flow, that might help me track down the problem.

**Comment by DavidTanner** [comment]
The comment is set up for each job.  Under Trigger Setup(to be renamed) -> Build Status Message, then you can set a message per status.

**Comment by robertfalconer** [comment]
Setting per job comments, instead of relying on the system default comments, still didn't work.

Presumably if the extension was having problems authenticating on github with the "bot" user, it would log an error, but I'm not seeing anything in the logs after `main build action completed: SUCCESS` that suggests that it's trying or failing to post a comment.

**Comment by robertfalconer** [comment]
Ok, I have a bit more information on this. 

I regenerated a new OAuth token for the bot user that should post comments on the pull request. This didn't change anything, but today I'm seeing that the token is marked as _Never Used_. Knowing that it's not using the token means it's not getting as far as attempting the comment, and it's not a problem with the permissions on the repo, or similar. 

Under what circumstances does it make the decision to post the comment?

**Comment by DavidTanner** [comment]
There was a bug in the credentials lookup that has been addressed in 1.24.3, please update and see if the issue persists

**Comment by robertfalconer** [comment]
I've updated the plugin, and it has fixed the problem. Thanks very much!
