### ISSUE TITLE
Is it possible to disable "Merged build finished. Test PASSed." default comment

### ISSUE THREAD

**Issue by robbles** [janinko/ghprb#294]
How do I turn this off? It appears even when the template for this message is set to an empty string.

It's redundant for our team, and since the comments get posted into a chat channel, this creates a lot of noise when deploys are happening.

Thanks!

**Comment by DavidTanner** [comment]
On the global configuration section there are two checkboxes that specify comments should be used when status updates fail.  Make sure they are unchecked.

**Comment by robbles** [comment]
This is on build success that I'm talking about, not when status updates fail. Is it possible to disable the message I referenced in the title of this issue?

Or do those settings somehow affect those comments as well?
