### ISSUE TITLE
signature / X-Hub-Signature check does not work

### ISSUE THREAD

**Issue by waltherg** [janinko/ghprb#300]
I set up the GitHub webhook for Jenkins GH pull request builder appropriately and they are received by my Jenkins instance correctly.

I am running into the following issues:
- when in Jenkins options -> GitHub Auth I set shared secret to empty the Jenkins logs will insist that some local signature XXX does not match the external signature
- when I do set the shared secret and the secret in the GitHub webhook configuration panel to the same value then the Jenkins logs will still say that the internal and external signatures differ
- when I do not set a secret in the GitHub webhook panel then Jenkins will complain the the received request does not contain a signature

I am very confused by this behaviour since the the code that was introduced by the PR that introduced signature checks (https://github.com/janinko/ghprb/pull/239/files#diff-9c37d8872c2c0f06b92d2561f0d6bc1eR311) should not worry about signature checks if I do not specify a shared secret in Jenkins.

I further do not comprehend how the hash the GitHub and Jenkins produce could differ in the event that I do set both a Jenkins shared secret and a GH secret.

I also noticed that when resending the same packet multiple times through the GH webhooks interface then in my Jenkins logs the mismatched internal signature changes on every resend but the external (GitHub-generated) signature remains the same.

**Comment by waltherg** [comment]
Random fix for my issue: I changed the GitHub Server API URL (on the Jenkins systems setting page) from `https://api.github.com` to `https://api.github.com/`.

I am still getting `Local signature XYZ does not match external signature ABC` SEVERE messages in my logs but in addition to those I also get `Signatures checking OK` messages - both for the exact same event.

Very confusing and frustrating to set up but seems to work for me now.

**Comment by Suirtimed** [comment]
I believe I am having a very similar issue (if it's not identical), although I don't get a Signatures check OK message.

**Comment by Suirtimed** [comment]
I've removed some extra credentials that weren't needed and now I think I'm getting the same thing reported, but the PR builds aren't being triggered.  Log below:

Jul 07, 2015 1:43:17 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Local signature b3233964689515bfdb36e5eb2bec3f578e9563f8 does not match external signature 96763d5552669b4dac2f0a357516b7bba1b60075
Jul 07, 2015 1:43:17 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Local signature 06af98ed5d85dde85c086697d2f8c0304dfb327b does not match external signature 96763d5552669b4dac2f0a357516b7bba1b60075
Jul 07, 2015 1:43:17 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 07, 2015 1:43:17 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request

**Comment by DavidTanner** [comment]
You probably want to update the secret saved in jenkins to the one provided by GitHub?

**Comment by mboersma** [comment]
> when I do set the shared secret and the secret in the GitHub webhook configuration panel to the same value then the Jenkins logs will still say that the internal and external signatures differ

I have the same behavior, and it's stopped our builds from firing apparently.

> You probably want to update the secret saved in jenkins to the one provided by GitHub?

I've done that several times, but they continue to disagree on the signature check. Seems like a bug.

**Comment by mboersma** [comment]
^^ Awesome, I'll be glad to test that out when it lands in a newer plugin and let you know if it fixes our setup.

**Comment by Suirtimed** [comment]
I upgraded to 1.24.7 and it looks like I'm seeing different behavior in the logs but no job is being triggered still.  Log below:

Got payload event: pull_request
Jul 08, 2015 1:31:43 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for 739c9be5-87e2-461f-9684-323f8da783ed, using context zombie-common__PR_AllTest for url https://api.github.com/
Jul 08, 2015 1:31:43 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 08, 2015 1:31:43 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context zombie-common__PR_AllTest

**Comment by DavidTanner** [comment]
issue https://github.com/jenkinsci/ghprb-plugin/issues/134 brings up that a change to how the plugin handles the updatedDate caused comment processing to be broken.  Try with 1.24.8

**Comment by Suirtimed** [comment]
How do I get 1.24.8?  My plugins only shows 1.24.7 as current and downgrade to 1.24.5.  I'm more than willing to download/build/manually install :)

**Comment by DavidTanner** [comment]
On the last tab of the update center you can have jenkins check the update site again

**Comment by Suirtimed** [comment]
OK, I've updated to 1.24.8 and restarted.  After Jenkins came back up I did another push and the log below is from "All":

Jenkins is fully up and running
Jul 09, 2015 12:49:19 PM INFO com.cloudbees.jenkins.GitHubWebHook processGitHubPayload
Received POST for https://github.com/VMop/zombie-eh-capacity-planning-report
Jul 09, 2015 12:49:19 PM WARNING hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
Failed to instantiate optional component com.cloudbees.jenkins.GitHubRepositoryNameContributor$FromMultiSCM; skipping
Jul 09, 2015 12:49:19 PM INFO com.cloudbees.jenkins.GitHubWebHook processGitHubPayload
Poked Eh-capacity-planning-report_Trigger
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request





This is from the ghprb set to finest:

Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 09, 2015 12:49:20 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for 739c9be5-87e2-461f-9684-323f8da783ed, using context Eng-ch-zed-action-instance-plugin__PR_AllTest for url https://api.github.com
Jul 09, 2015 12:49:20 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 09, 2015 12:49:20 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context Eng-ch-zed-action-instance-plugin__PR_AllTest
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 09, 2015 12:49:20 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for 739c9be5-87e2-461f-9684-323f8da783ed, using context Eh-capacity-planning-report__PR_AllTest for url https://api.github.com
Jul 09, 2015 12:49:20 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 09, 2015 12:49:20 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context Eh-capacity-planning-report__PR_AllTest
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 09, 2015 12:49:20 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for 739c9be5-87e2-461f-9684-323f8da783ed, using context zombie-common__PR_AllTest for url https://api.github.com
Jul 09, 2015 12:49:20 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 09, 2015 12:49:20 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context zombie-common__PR_AllTest
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 09, 2015 12:49:20 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for 739c9be5-87e2-461f-9684-323f8da783ed, using context Eng-ch-zed-action-instance__PR_AllTest for url https://api.github.com
Jul 09, 2015 12:49:20 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 09, 2015 12:49:20 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context Eng-ch-zed-action-instance__PR_AllTest
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 09, 2015 12:49:20 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 09, 2015 12:49:20 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for 739c9be5-87e2-461f-9684-323f8da783ed, using context zombie-orchestration-execution__PR_AllTest for url https://api.github.com
Jul 09, 2015 12:49:20 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 09, 2015 12:49:20 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context zombie-orchestration-execution__PR_AllTest

**Comment by Suirtimed** [comment]
I've noticed that I don't think I have the same credential Id in all of the "different" places that I can have one selected from the drop down boxes.  It looks like the one available in the job isn't even able to see the one in the global Jenkins config and vice-versa.

**Comment by DavidTanner** [comment]
Can @waltherg or @mboersma verify if this is working now?  @Suirtimed I am not sure what you mean, but it appears to be working correctly for you now.  If you mean that the credentials lists are different that is because they are. The drop down on the global page shows the actual credentials, and the drop down in the job lists the auth settings you created on the global configure page.

**Comment by Suirtimed** [comment]
@DavidTanner It's not building anything.  The job isn't being triggered.  In the 
Manage Jenkins -> Credentials
 I have "Global Credentials" and "api.github.com" credential domains  Under the api.github.com credential domain I have just one credential that is github.com OAuth based.  Under the Global Credentials I have 6 different credentials that are various combinations of username/password, OAuth, and key based credentials.

On the system configuration page:
Github Web Hook uses it's own username and OAuth token value

Github Pull Request Builder,
I have a shared secret and a drop down based credential based on github.com OAuth

On one of the jobs that I intend to be triggered by PR:

Source Code Management for Git uses an OAuth credential (Only five credentials are visible there) (I'm using a key based one)

Github Pull Request Builder only has one option for the OAuth token under api.github.com

**Comment by Suirtimed** [comment]
If I test credentials I get: Connected to https://api.github.com as null

Should it be null or should it have a value like the github.com username?

**Comment by DavidTanner** [comment]
So the null is when it tries getName(), I can change that to use the login instead, but it just looks like you don't have any PR's coming through that are set to be triggered.  Can you send me the job configuration?

**Comment by DavidTanner** [comment]
https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.24.8/src/main/java/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth.java#L285

**Comment by Suirtimed** [comment]
I scrubbed some stuff with ###A foo I removed###

https://gist.github.com/Suirtimed/b16386df0eb6d0ce5dba

My intent for this particular job is to trigger any PRs against the development branch

**Comment by DavidTanner** [comment]
If you want any PR against develop to run, I think you have to check the build all checkbox.  I will dig through the logic some more tonight to make sure.

**Comment by Suirtimed** [comment]
I checked the box next to "Build every pull request automatically without asking (Dangerous!)." and tried the build again by using the issue comment mechanism and it did not work.  I restarted jenkins and added another commit to an open PR with no build being triggered.  I tried adding the trailing slash to the api.github.com url and tried again...

Jul 10, 2015 10:14:02 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 10, 2015 10:14:02 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 10, 2015 10:14:02 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ce8d7e7f-ef67-49c7-ae8c-b2fc38ba839d, using context zombie-orchestration-execution__PR_AllTest for url https://api.github.com
Jul 10, 2015 10:14:02 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 10, 2015 10:14:02 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context zombie-orchestration-execution__PR_AllTest
Jul 10, 2015 10:14:02 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 10, 2015 10:14:02 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 10, 2015 10:14:02 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ce8d7e7f-ef67-49c7-ae8c-b2fc38ba839d, using context Eh-capacity-planning-report__PR_AllTest for url https://api.github.com
Jul 10, 2015 10:14:02 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 10, 2015 10:14:02 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context Eh-capacity-planning-report__PR_AllTest
Jul 10, 2015 10:14:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 10, 2015 10:14:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 10, 2015 10:14:03 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ce8d7e7f-ef67-49c7-ae8c-b2fc38ba839d, using context zombie-common__PR_AllTest for url https://api.github.com
Jul 10, 2015 10:14:03 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 10, 2015 10:14:03 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context zombie-common__PR_AllTest
Jul 10, 2015 10:14:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 10, 2015 10:14:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 10, 2015 10:14:03 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ce8d7e7f-ef67-49c7-ae8c-b2fc38ba839d, using context Eng-ch-zed-action-instance-plugin__PR_AllTest for url https://api.github.com
Jul 10, 2015 10:14:03 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 10, 2015 10:14:03 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context Eng-ch-zed-action-instance-plugin__PR_AllTest
Jul 10, 2015 10:14:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 10, 2015 10:14:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 10, 2015 10:14:03 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ce8d7e7f-ef67-49c7-ae8c-b2fc38ba839d, using context Eng-ch-zed-action-instance__PR_AllTest for url https://api.github.com
Jul 10, 2015 10:14:03 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 10, 2015 10:14:03 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context Eng-ch-zed-action-instance__PR_AllTest
Jul 10, 2015 10:15:15 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 10, 2015 10:15:15 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 10, 2015 10:15:15 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ce8d7e7f-ef67-49c7-ae8c-b2fc38ba839d, using context Eh-capacity-planning-report__PR_AllTest for url https://api.github.com/
Jul 10, 2015 10:15:15 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 10, 2015 10:15:15 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context Eh-capacity-planning-report__PR_AllTest
Jul 10, 2015 10:15:15 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 10, 2015 10:15:15 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 10, 2015 10:15:15 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ce8d7e7f-ef67-49c7-ae8c-b2fc38ba839d, using context Eng-ch-zed-action-instance__PR_AllTest for url https://api.github.com/
Jul 10, 2015 10:15:15 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 10, 2015 10:15:15 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context Eng-ch-zed-action-instance__PR_AllTest
Jul 10, 2015 10:15:15 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 10, 2015 10:15:15 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 10, 2015 10:15:15 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ce8d7e7f-ef67-49c7-ae8c-b2fc38ba839d, using context Eng-ch-zed-action-instance-plugin__PR_AllTest for url https://api.github.com/
Jul 10, 2015 10:15:15 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 10, 2015 10:15:15 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context Eng-ch-zed-action-instance-plugin__PR_AllTest
Jul 10, 2015 10:15:15 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 10, 2015 10:15:15 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 10, 2015 10:15:15 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ce8d7e7f-ef67-49c7-ae8c-b2fc38ba839d, using context zombie-orchestration-execution__PR_AllTest for url https://api.github.com/
Jul 10, 2015 10:15:15 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 10, 2015 10:15:15 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context zombie-orchestration-execution__PR_AllTest
Jul 10, 2015 10:15:15 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
Signatures checking OK
Jul 10, 2015 10:15:15 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jul 10, 2015 10:15:15 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ce8d7e7f-ef67-49c7-ae8c-b2fc38ba839d, using context zombie-common__PR_AllTest for url https://api.github.com/
Jul 10, 2015 10:15:15 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 7 credentials
Jul 10, 2015 10:15:15 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context zombie-common__PR_AllTest

**Comment by DavidTanner** [comment]
@Suirtimed Since I think this is a case problem.  When the webhook compares the repo names, one has caps the other doesn't.

**Comment by DavidTanner** [comment]
```
    private boolean matchRepo(GhprbRepository ghprbRepo, GHRepository ghRepo) {
        return ghprbRepo.getName().equals(ghRepo.getFullName());
    }
```

**Comment by Suirtimed** [comment]
Awesome!  I hope that works.  I'll get the update as soon as I can and let you know.

**Comment by Suirtimed** [comment]
I got the update and a comment did trigger a PR.  I'll continue testing :)  Thanks @DavidTanner !
