### ISSUE TITLE
Create API Token

### ISSUE THREAD

**Issue by williamboman** [janinko/ghprb#304]
When trying to create an API token through the `GitHub Pull Request Builder` section in `Manage Jenkins` I get a `No username/password credentials provided` error when pressing the `Create Token` button.

I've filled in the `Username temp` and `Password temp` fields and looking at the HTTP request, it does send these values.

`ghprb@1.24.5`
`GitHub API@1.68`
`jenkins@1.596.2`

**Comment by williamboman** [comment]
Started working again after removing the server configuration. Might've been due to having an already configured secret key/auth id..

**Comment by csmart** [comment]
I've had this today too; once when initially setting it up on a test repo and a second time for the real repo. The test repo worked after I added something into description, but that didn't work the second time; I had to manually create a token and modify the existing working one under credentials in Jenkins.

**Comment by williamboman** [comment]
Yeah it's definitely unintuitive.

**Comment by csmart** [comment]
Yeah I couldn't actually get the second one to go and I don't know why the first one worked, because adding the description was a coincidence, I think. Adding that to the second one didn't work. Deleting all the servers and adding a new one didn't work.
