### ISSUE TITLE
can't change github api credentials

### ISSUE THREAD

**Issue by toejough** [janinko/ghprb#308]
The only option I have for credentials in this plugin seems to be anonymous, which is not sufficient to access my private repo:
![screen shot 2015-07-10 at 11 55 37 am](https://cloud.githubusercontent.com/assets/5317312/8622819/4fa6e6f6-26fb-11e5-93bb-5c0c628002e9.png)

The dropdown only has this one option, and there's no "add" or "plus" or "advanced" field here to click on and add credentials.

I do have valid user credentials configured under the "Git" section of the SCM section:
![screen shot 2015-07-10 at 12 03 39 pm](https://cloud.githubusercontent.com/assets/5317312/8622979/8fcd2b90-26fc-11e5-8f75-448e20644e96.png)

**Comment by toejough** [comment]
Here's another screenshot showing no options for changing my creds:

![screen shot 2015-07-10 at 12 12 25 pm](https://cloud.githubusercontent.com/assets/5317312/8623043/018c470c-26fd-11e5-98d0-bedb3fe77a6b.png)

Has anyone seen this before?  How do I add my credentials such that this plugin will use them?

**Comment by DavidTanner** [comment]
You need to set up credentials for the Pull Request plugin on the global config page, not the job git section.  Once you have something set globally then it will show up by default in each job.

**Comment by DavidTanner** [comment]
Credentials that you add for the GitSCM may/may not be available to use in the pull request builder, you still have to set them up on the global config page though.

**Comment by toejough** [comment]
Hey, thanks for the quick response, but...

It was added in the global credentials, and just selected in the git config section to show that it was available).

At the menu path /main/manage-jenkins/manage-credentials:
![screen shot 2015-07-10 at 1 45 17 pm](https://cloud.githubusercontent.com/assets/5317312/8625063/503fcb1e-270a-11e5-9b7f-538a69f03e44.png)

We have other github plugins installed which are using these credentials just fine.  Is there some other config?

**Comment by DavidTanner** [comment]
That is the global credentials config, but you need to tell the plugin to use it on the jenkins global config page.  There you pick your credentials and set the githup api

**Comment by toejough** [comment]
ah, that did it for me.  Thank you for your time!

**Comment by DavidTanner** [comment]
Glad to hear it!  Thanks for the bug report!
