### ISSUE TITLE
Build started status not applied to job configuration

### ISSUE THREAD

**Issue by mariusioana** [janinko/ghprb#310]
Hi,

I have the following situation:
- created a jenkins job with ghrb configuration
- after the job configuration, went to the global jenkins configuration and added also a custom message for "Commit Status Build Started"

In github, I always see while the build is running the following detailed message:
Build started sha1 is merged. which comes from:
if (StringUtils.isEmpty(startedStatus)) {
            sb.append("Build started");
            sb.append(c.isMerged() ? " sha1 is merged." : " sha1 is original commit.");

Why am I not able to set that custom commit status build started message? I fail to understand why it would not work from reading the code.

Thanks,
Marius

**Comment by DavidTanner** [comment]
There is a project level setting, and a global default.   You set the global default, which will populate into a job when you create the project setting.  The global default only takes effect when you first add the local setting.

**Comment by dtothefp** [comment]
seems strange that `'sha 1'` is hardcoded and not interpolated as the commit sha. Other than changing global/local defaults is there a way to interpolated this commit sha?
