### ISSUE TITLE
GitHub API credentials is always set to the first entry

### ISSUE THREAD

**Issue by crawford** [janinko/ghprb#319]
Whenever I load my job settings, the "GitHub API credentials" is set to the first available choice in the drop-down, regardless of the last saved entry. Unless I correct this entry ever time I save, it will be updated (incorrectly) to the first available entry.

**Comment by JensTimmerman** [comment]
I'm seeing the same issue here.

**Comment by pviniciusfm** [comment]
Same Issue here

**Comment by JensTimmerman** [comment]
I even have to click 'save' for this to be applied, clicking apply seems also to apply the first entry everytime.
