### ISSUE TITLE
Ability to specify Hostname

### ISSUE THREAD

**Issue by FlYnN91** [janinko/ghprb#321]
GitBucket setup on IIS requires context path making full URL to be http://domain/gitbucket.
The ghprb gets confused by the additional parameter. If a repository path is "http://domain/gitbucket/Utilities/UniversalTestApplication.git", it thinks that the "/gitbucket" is owner and 
"/Utilties" is the repo name, but it isn't. Jenkis log shows
```
 "Could not retrieve GitHub repository named gitbucket/Utilities (Do you have properly set 'GitHub project' field in job configuration?)"
```
It would be great if there was a way to set host name which the ghprb could utilize.

Thanks

**Comment by DavidTanner** [comment]
Right now it is just using a regex, so that would be why it doesn't work.  I think it would be good if the plugin stopped relying on the GitHub status updater.

**Comment by FlYnN91** [comment]
@DavidTanner thanks for the update. I guess I would have to fork the project, change the regex and re-compile.

**Comment by FlYnN91** [comment]
I have solved my issue by making GitBucket run as http://domain/ and not http://domain/gitbucket
