### ISSUE TITLE
ghprbPullLongDescription causes Windows builds to break

### ISSUE THREAD

**Issue by marcocast** [janinko/ghprb#322]
Hi,

We have a Jenkins job configured with the ghprb plugin to run builds against a matrix of slaves (Linux,Mac, Windows).

Linux and Mac environments work well, but in windows we noticed a problem related with the ghprbPullLongDescription system property passed  at execution time. 
The problem is that there are multiple git comments joined together, but separated by a break line that is badly handled by Windows OS. 

It would be good to be able to optionally remove some of the properties defined in the GhprbTrigger.startJob 

Thanks

Marco

**Comment by vorburger** [comment]
Same problem here.. more details: The -DghprbPullLongDescription intro. https://github.com/jenkinsci/ghprb-plugin/pull/105 can cause errors such as:

    [master-build] $ cmd.exe /C '"C:\EDS\ant\ant-1.9.0.dist\bin\ant.bat -file build.xml -DghprbCommentBody=null -DghprbTriggerAuthorEmail="" -DghprbTargetBranch=master -DghprbSourceBranch=DS-9174_headlessELangTAP_final "-DghprbActualCommitAuthor=Michael Vorburger" -Dsha1=origin/pr/1067/merge "-DghprbPullLongDescription=BLA BLA
    BLA BLA _very_ long...
    ... multi line description" -DghprbPullLink=https://github.com/TemenosDS/DS/pull/1067 -DghprbActualCommit=bfdd7a70b5d69879d74162eea1a58512e1ece08b -DghprbTriggerAuthorLoginMention="" -DGIT_BRANCH=DS-9174_headlessELangTAP_final -DghprbPullAuthorEmail=michael.vorburger+github-profile@gmail.com -DghprbPullAuthorLogin=vorburger -DghprbActualCommitAuthorEmail=mvorburger@temenos.com -DghprbTriggerAuthor="" -DghprbTriggerAuthorLogin="" -DghprbPullId=1067 "-DghprbPullTitle=DS-9174 DS Generator failing with 'The method ==(boolean) is undefined'" -DghprbPullAuthorLoginMention=@vorburger "-DghprbPullDescription=GitHub pull request #1067 of commit bfdd7a70b5d69879d74162eea1a58512e1ece08b, no merge conflicts." -Dds.skip.40-Plugins-Build=false -Dskip.62-Big-Tests--TAP-Models-Generation=true -Dds.remote.build=true -Dds.skip.63-Medium-Tests--T24-Models-Generation-and-Packaging=false -Dds.skip.10-Prepare-Dependencies=false -Dds.skip.50-Small-Tests--Unit-Tests=false -Dds.skip.15-b2-Templates=false -Dskip.65-Big-Tests--BM-Maven-Generation=true -Dds.skip.73-Big-tests--Component-Framework-Integration-Test=false -Dds.p2cache.location.relative=../../ds.p2.repo.cache -Dds.skip.72-Big-Tests--Hothouse-Fully-Loaded-Test=true -Dds.skip.30-Documentation=false -Dds.skip.71-Big-Tests--Hothouse-Test=true -Dsun.net.client.defaultConnectTimeout=10000 -Dds.skip.68-Big-Tests--T24-External-Tests=false -Dds.skip.60-Products-Only-Build=false -Dds.skip.09-T24-Maven=false -Dds.skip.99-Final-Cleanup=true -Dsun.net.client.defaultReadTimeout=10000 -Dds.skip.69-Big-Tests--TAP-External-Tests=false -Dds.skip.61-Runtime-Build=false build-all-online && exit %%ERRORLEVEL%%"'
    The syntax of the command is incorrect.
    Build step 'Invoke Ant' marked build as failure

How about simply trimming the content of -DghprbPullLongDescription if exceeding some max length? Only on Windows slaves if that information, or just everywhere, is that a problem? Or does Jenkins have some better built-in lower level support to deal with max. length of exec problems on Windows? (Like creating an intermediate script approach?)

Would a pull request from us proposing this be welcome and be merged?

**Comment by DavidTanner** [comment]
I am thinking of escaping newline characters.  Would that be an acceptable fix?  I don't think it is the length, but if that is the case then there needs to be a way to specify what you want for each job, or something like that.

**Comment by vorburger** [comment]
You may be right, problem could be newlines not length actually. Try and
we'll see!
