### ISSUE TITLE
${sha1} env variable doesn't work correctly

### ISSUE THREAD

**Issue by rustybailey** [janinko/ghprb#330]
I'm having trouble locating the actual source of the problem, but I will tell you what I do know. In Jenkins, we recently had several Git-related plugins updated:
- [Git plugin](https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin): 2.2.7 -> 2.4.0
- [GitHub plugin](https://wiki.jenkins-ci.org/display/JENKINS/Github+Plugin): 1.9.1 -> 1.13.3
- [GitHub Pull Request Builder](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin): 1.16-5 -> 1.27

After that happened, any jobs that were referencing the `${sha1}` variable for the "Branch Specifier" said this in the console output and errored out:
```
09:29:54 using GIT_SSH to set credentials 
09:29:54  > C:\Program Files (x86)\Git\bin\git.exe -c core.askpass=true fetch --tags --progress git@github.com:repoowner/somereponame.git +refs/pull/*:refs/remotes/origin/pr/*
09:30:24  > C:\Program Files (x86)\Git\bin\git.exe rev-parse "{origin/pr/63/merge}^{commit}" # timeout=10
09:30:24  > C:\Program Files (x86)\Git\bin\git.exe rev-parse "refs/remotes/origin/{origin/pr/63/merge}^{commit}" # timeout=10
09:30:24  > C:\Program Files (x86)\Git\bin\git.exe rev-parse "{origin/pr/63/merge}^{commit}" # timeout=10
09:30:24 ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
```

Then I changed it to `$sha1`, and it seems to work correctly:
```
10:25:05 using GIT_SSH to set credentials 
10:25:05  > C:\Program Files (x86)\Git\bin\git.exe -c core.askpass=true fetch --tags --progress git@github.com:repoowner/somereponame.git +refs/pull/*:refs/remotes/origin/pr/*
10:25:36  > C:\Program Files (x86)\Git\bin\git.exe rev-parse "refs/remotes/origin/pr/63/merge^{commit}" # timeout=10
10:25:36  > C:\Program Files (x86)\Git\bin\git.exe rev-parse "refs/remotes/origin/origin/pr/63/merge^{commit}" # timeout=10
10:25:36 Checking out Revision bc1e977a7ef8ad5f04cc9d5ff569e5b9aeb137bc (refs/remotes/origin/pr/63/merge)
```

If `$sha1` is now the correct variable name to use in "Branch Specifier", I would recommend changing the README.md to indicate that (and maybe also note that it has changed). If this is a bug, and `${sha1}` should still work, maybe something broke between versions in one of those other Git plugins?

**Comment by DavidTanner** [comment]
That is really bad, $sha1 should be equal to ${sha1}.  If it is not working this is an issue with the Git plugin.  Please open an issue with them, or it is possibly a Jenkins issue.  Are you sure you didn't have an extra {} around it?

**Comment by DavidTanner** [comment]
like {${sha1}}

**Comment by rustybailey** [comment]
No, didn't have brackets around it. Opened issue in Git plugin here: https://issues.jenkins-ci.org/browse/JENKINS-30594

**Comment by DavidTanner** [comment]
Can you post that section of the job config.xml? With the ${sha1} that is causing the issue.

**Comment by rustybailey** [comment]
Nevermind... I changed it back to `${sha1}` and it seems to be working again. Don't know why that was happening...

**Comment by meruvasivakumari** [comment]
I configured in ref spec both +refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/* 
but only pull request is been build for actual branch it is reporting 

 git rev-parse origin/${sha1}^{commit} # timeout=10
 > git rev-parse ${sha1}^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE
