### ISSUE TITLE
Pull Request Trigger only if changed file matches a regex

### ISSUE THREAD

**Issue by nitinpadalia** [janinko/ghprb#337]
I want to use this plugin with a maven multi maven project. I've different jobs for each of my module, I would be invoking each job for a pull request using some phrase like 'please test'. Appropriate job should be triggered based on which files changed; e.g.; if I have two folders mod1 and mod2 then jobs job1 and job2 respectively then if I raise a pull request and issue a comment in pull request 'please test' then job1 should trigger if pull request has file changes as mod1/* and if file changes are in mod2/* then job2 should be triggered. 

Is this possible with this plugin? or can we add support like we've in polling scm plugin for include or exclude regions.

**Comment by DavidTanner** [comment]
Not sure if this is possible, but I will do some research

**Comment by nitinpadalia** [comment]
Ok I raised this issue in original branch as well so closing this duplicate one. https://github.com/jenkinsci/ghprb-plugin/issues/205
