### ISSUE TITLE
"Manage hooks" not respected? 

### ISSUE THREAD

**Issue by packplusplus** [janinko/ghprb#342]
I think ghprb is adding webhooks to the repo regardless of the setting to manageHooks in the git plugin. Bug or does ghprb ignore that value? 

Jenkins 1.631
GIT client plugin 1.19.0
GIT plugin 2.4.0
GitHub API Plugin 1.69
GitHub plugin 1.13.3
GitHub Pull Request Builder 1.29

```
<?xml version='1.0' encoding='UTF-8'?>
<github-plugin-configuration plugin="github@1.13.3">
  <configs>
    <github-server-config>
      <apiUrl>https://api.github.com</apiUrl>
      <manageHooks>false</manageHooks>
      <credentialsId>DONTSTEALMYUUIDBRO</credentialsId>
    </github-server-config>
  </configs>
</github-plugin-configuration>
```

(the gui matches)

**Comment by DavidTanner** [comment]
As it is programed right now if there is a webhook for jenkins, all jobs will be triggered.  I have been wondering if this was desirable, if it should be changed to have one webhook per job instead, or if the trigger should be set to ignore hooks if it isn't configured to use them.

**Comment by packplusplus** [comment]
> As it is programed right now if there is a webhook for jenkins, all jobs will be triggered.
The all jobs thing is a bit of an issue, but we code around it. 

My issue is jenkins is creating webhooks regardless of `<manageHooks>false</manageHooks>` being set.

**Comment by packplusplus** [comment]
Closing, I lost context of if this is still an issue and don't want to clutter up the issues history.
