### ISSUE TITLE
Errors when running Jenkins 

### ISSUE THREAD

**Issue by danyaljj** [janinko/ghprb#356]
I have Jenkins setup. Everything seem to be working fine, except that the build for Pull Requests do not seem to work the changes in the PR. 
Like it seems it only compiles the master branch in the main repository. Even if you have syntax bug in your PR, it would still pass the jenkins test.  
Anyone has faced this problem before? Any advice / suggestions?

BTW, I noticed that when I start Jenkins `ghprb` gives me some errors: 

<img width="1100" alt="screen shot 2015-11-06 at 8 51 10 pm" src="https://cloud.githubusercontent.com/assets/2441454/11013184/2efa6a2e-84c8-11e5-9588-ab1db1a4243a.png">

**Comment by DavidTanner** [comment]
The error is correct, you are using an ssh endpoint instead of a url.

**Comment by danyaljj** [comment]
I see, but still confused.  Should use  `https://github.com/IllinoisCogComp/open-eval.git`, or `https://github.com/IllinoisCogComp/open-eval`?   (instead of `git@github.com:IllinoisCogComp/open-eval.git`)

**Comment by danyaljj** [comment]
And which of the two addresses in the configuration should be changed to url? (one says `GitHub project`, and the other `Repository URL`; I suppose the former, since Jenkins automatically adds `/` at its end). 
<img width="1410" alt="screen shot 2015-11-06 at 9 22 59 pm" src="https://cloud.githubusercontent.com/assets/2441454/11013289/96491384-84cc-11e5-84af-2fe8f1639662.png">

**Comment by DavidTanner** [comment]
GitHub project expects the url, the Repository URL can be either a url or ssh endpoint as it is the actual git implementation

**Comment by danyaljj** [comment]
Ah ok.It's confusing. So I did it as you can see.
<img width="1384" alt="screen shot 2015-11-06 at 9 48 44 pm" src="https://cloud.githubusercontent.com/assets/2441454/11013361/2fff9388-84d0-11e5-89fa-ced1d9e434aa.png">

But the problem is that I am still getting unreasonable results. 
Like see this PR contains a syntax error and Semaphore rightly fails on it: 
https://github.com/danyaljj/jwnl-prime/pull/1
Although Jenkins is, surprisingly, successful.

**Comment by danyaljj** [comment]
@DavidTanner so I fixed the urls and now it does NOT give me any errors when starting the Jenkins. 
Here is the full run log: 
```
[khashab2@silverbridge illinois-cogcomp-nlp]$ screen -dr jenkins

INFO: Started initialization
Nov 07, 2015 9:34:16 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Nov 07, 2015 9:34:16 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Nov 07, 2015 9:34:16 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Nov 07, 2015 9:34:16 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Nov 07, 2015 9:34:16 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Nov 07, 2015 9:34:16 PM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Nov 07, 2015 9:34:16 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
Nov 07, 2015 9:36:01 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #2 was updated on danyaljj/jwnl-prime at 11/7/15 9:35 PM by User:danyaljj
Nov 07, 2015 9:36:04 PM org.jenkinsci.plugins.ghprb.GhprbTrigger stop
INFO: Stopping the ghprb trigger for project jwnl-prime
Nov 07, 2015 9:36:04 PM org.jenkinsci.plugins.ghprb.GhprbTrigger start
INFO: Starting the ghprb trigger for the jwnl-prime job; newInstance is true
Nov 07, 2015 9:36:05 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
WARNING: Request not known
Nov 07, 2015 9:37:01 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking issue comment 'org.kohsuke.github.GHIssueComment@8de31e5' for repo danyaljj/jwnl-prime
Nov 07, 2015 9:37:01 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handleComment
INFO: Checking comment on PR #1 for job jwnl-prime
Nov 07, 2015 9:37:01 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #1 was updated on danyaljj/jwnl-prime at 11/7/15 9:36 PM by User:danyaljj
Nov 07, 2015 9:37:09 PM hudson.model.Run execute
INFO: jwnl-prime #6 main build action completed: SUCCESS
Nov 07, 2015 9:37:56 PM hudson.model.Run execute
INFO: jwnl-prime #7 main build action completed: SUCCESS
```
But the main issue still remains: it does not correctly build the pull requests. Like [this PR](https://github.com/danyaljj/jwnl-prime/pull/1) has a syntax error, but still builds it without errors.

**Comment by DavidTanner** [comment]
Your job doesn't actually do anything, so that would be why it passes.  You need to set a goal for maven to do.
