### ISSUE TITLE
Trigger phrase being modified when job is saved - regex literals

### ISSUE THREAD

**Issue by mikewaters** [janinko/ghprb#364]
Sometimes when saving a job configuration, regex literals are appended and prepended to the job's ghprb trigger phrase.  This causes our triggers to not work until the phrase is fixed.

<img width="1015" alt="screen shot 2015-11-20 at 9 35 06 am" src="https://cloud.githubusercontent.com/assets/149978/11302216/0ea77e9a-8f6a-11e5-82e9-367bfcacff82.png">

Is this a known problem/feature?  I could not find anything in Jira or github issues.

Thank you.

Jenkins 1.638 / ghprb 1.29

**Comment by DavidTanner** [comment]
Known issue, please update to latest ghprb.  It will happen once more then go away.

**Comment by mikewaters** [comment]
Thank you.
