### ISSUE TITLE
Not able to choose any credentials.

### ISSUE THREAD

**Issue by ruseinov** [janinko/ghprb#367]
I do have credentials in global scope, github api works fine from global jenkins config, but when I configure a PR job http://uploadr.obnovlenie.ru/uploads/lazycoder-2015-11-23-191239.png I can't choose any credentials and therefore get FileNotFound errors.

Been rebooting/reshuffling a lot, didn't help.

**Comment by DavidTanner** [comment]
The credentials need to be set up on the global configure page first, then they will show up in the job config.  If they are set up, please post the relevant portion of your global config.xml file.

**Comment by ruseinov** [comment]
Hello @DavidTanner . Yes, they are added, here's a screenshot http://uploadr.obnovlenie.ru/uploads/lazycoder-2015-11-24-092938.png

**Comment by DavidTanner** [comment]
They need to be set up as part of the github pull request builder config.  Just adding the credentials to jenkins isn't enough.

**Comment by ruseinov** [comment]
How do I do that?

**Comment by ruseinov** [comment]
@DavidTanner I do have this http://uploadr.obnovlenie.ru/uploads/lazycoder-2015-11-24-160444.png setup, does not help me though, the job dropdown contains only anonymous access.

**Comment by ruseinov** [comment]
Okay, I finally found it!

**Comment by amerikan** [comment]
@ruseinov I've come across this issue too. Do you mind sharing how you were able to setup the credential for ghpr? 

I have already setup up the credential using jenkins Credentials. However, it's not appearing in the dropdown for some reason.

![screen shot 2016-01-11 at 12 16 21 pm](https://cloud.githubusercontent.com/assets/179356/12245455/6766cba0-b85d-11e5-9cc2-3198e29f3bae.png)

**Comment by ruseinov** [comment]
@amerikan The problem is that you have to add them through the plugin. Now that I have them setup it's not clear again how I did, but I remember that I just had to scroll down the jenkins config page to find out that there is a way to generate/enter these.

The UI is quite incomprehensive, I've been struggling with that a lot before managed to figure it out.

You cannot add these credentials via Jenkins credentials.

**Comment by amerikan** [comment]
@ruseinov thanks! I just figured it out. I went into Github.com settings page. Then to **Personal access tokens** and generated a token there. I then copied the hash it gave me and went back to Jenkins UI. Went to **Manage Jenkins** > **Configure System**. Then scrolled down to the **GitHub Pull Request Builder** section and click on the **Add**. From here I chose **Secret text** from dropdown for **Kind**. I pasted the hash I generated earlier into the **Secret** field. It then worked.

**Comment by ruseinov** [comment]
@amerikan Yes! Once you know where to look it's easier indeed :) No problem man.

**Comment by timjrobinson** [comment]
@amerikan Thanks I had the same issue and your solution worked perfectly. It should be in the readme.

**Comment by zirho** [comment]
There's no **GitHub Pull Request Builder** anymore.
Blocked again.

**Comment by brunoterkaly** [comment]
Does anyone have clear steps to kicking off a pipeline based on a Github commit? This should be the easiest thing the world and yet feels too painful. I'm find errors, different versions and more. Much of the guidance is dated that I run across.

Any help appreciated.

Stack trace
java.lang.NullPointerException
	at com.cloudbees.plugins.credentials.impl.BaseStandardCredentials$BaseStandardCredentialsDescriptor.doCheckId(BaseStandardCredentials.java:203)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
