### ISSUE TITLE
Unrendered HTML in build history

### ISSUE THREAD

**Issue by devotox** [janinko/ghprb#371]
<img width="373" alt="screenshot 2015-11-30 09 43 49" src="https://cloud.githubusercontent.com/assets/2064846/11468381/ebf92882-9746-11e5-8e00-ccbc587ae801.png">

**Comment by AviBueno** [comment]
+1 Having the exact same issue.

**Comment by jlebon** [comment]
Most likely this: https://github.com/jenkinsci/ghprb-plugin/issues/162

**Comment by AviBueno** [comment]
@jlebon indeed this fixes the issue, but the cost is undermining a global security flag.
As an alternative, is there a way to manually configure the description template in order to to strip out the HTML tags?

**Comment by blbradley** [comment]
@jlebon So, will the data will render after new version is distributed?

**Comment by devotox** [comment]
no@blbradley if you follow this steps though it will render correctly

This may be due to the Markup Formatter being set to Escaped HTML. If that is the case, you can change this by going to "Configure Jenkins" --> "Configure Global Security" --> "Markup Formatter" --> "Raw HTML" (at the expense of slightly less security).

**Comment by devotox** [comment]
no @blbradley if you follow this steps though it will render correctly

This may be due to the Markup Formatter being set to Escaped HTML. If that is the case, you can change this by going to "Configure Jenkins" --> "Configure Global Security" --> "Markup Formatter" --> "Raw HTML" (at the expense of slightly less security).

**Comment by jose-lpa** [comment]
For future visitors of this issue, in Jenkins 2 you can use "Safe HTML" option, which allows to render HTML but parses it before to remove potential unsafe stuff like ``<script>`` tags.

So, follow @jlebon instructions, but choose "Safe HTML" option instead of "Raw HTML".

![jenkins_safe_html](https://cloud.githubusercontent.com/assets/2226098/19686399/d8b86c6c-9ab8-11e6-9955-46fbc489e8f0.png)

**Comment by devotox** [comment]
Yes @jose-lpa is correct and this can now be closed
