### ISSUE TITLE
Ability to cancel queued jobs if the branch has already been merged

### ISSUE THREAD

**Issue by alextreppass** [janinko/ghprb#373]
Hi, 

My org usually updates the PR against master before merging (Github Enterprise provides a one-click button to do this). This operation queues a PR build, which we don't care too much about the results of.

Is there a way we can achieve a 'cancel job if PR was already merged' check at the start of each pull request builder job?

**Comment by DavidTanner** [comment]
Was just released today from jenkinsci

**Comment by karlhorky** [comment]
@DavidTanner what is this option called in the configuration? Or is this the default now?

I can't seem to find it on either of these pages:
https://github.com/janinko/ghprb/blob/master/README.md
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin
