### ISSUE TITLE
Test results are not updated in the Commit Message for downstream jobs

### ISSUE THREAD

**Issue by devashish2203** [janinko/ghprb#390]
The following is my Job setup in Jenkins

Job 1: Trigerred for every PR raised on my Repo. On completion this triggers two other downstream jobs Job2(Unit tests) and Job3 (UI Tests)

All 3 jobs are updating the commit status with different commit status context. The issue is that while the First job updates the status with the Right commit message it also adds the test results summary as well to the commit status. While the downstream jobs only update the message as specified in the Commit Status Build Status and do not report the test results summary.

All 3 jobs are publishing a JUnit report of the test results.

Screenshot of the commit statuses.
<img width="976" alt="screen shot 2016-02-22 at 4 30 54 pm" src="https://cloud.githubusercontent.com/assets/7950196/13216563/9e8f6498-d982-11e5-9e36-2a6c082f2807.png">

**Comment by jayeshkhairnar** [comment]
@devashish2203 Could you please let me know how you setup git status checkes for downstream job i.e test UI

**Comment by devashish2203** [comment]
@jayeshkhairnar If I remember correctly, what I had done here is that the first job (Jenkins Build Debug) was triggered using this plugin whenever a pull request was created/updated.
The other two jobs were configured as jobs to be executed on successful completion of the above job.
The reporting to Github happens the same way it does for the first job by selecting checkbox  Set build status for Github Pull Request".

P.S. I've not been using this plugin for quite some time, since we moved away from Github for our repos, so there might be some changes in the newer versions of the plugin that I'm not aware off.

**Comment by jayeshkhairnar** [comment]
@devashish2203 I am doing same way but my test UI job using different repo, So git status not update once test UI job finish. I was refer link [https://stackoverflow.com/questions/38746336/proper-configuration-for-jenkins-github-pull-request-builder-downstream/38750377#38750377]. Please advise me if any other way we can do this.
