### ISSUE TITLE
Force pushes/rebases do not cancel ongoing builds

### ISSUE THREAD

**Issue by jasonmadigan** [janinko/ghprb#391]
I've been encountering a pretty awful problem over the past few months. If PRs are rebased or force push'd to while a build is ongoing, the existing (and now out of date) job will continue to build. If several changes are force pushed in quick succession, you'll end up with a long build queue of builds which are going nowhere (this gets more painful if builds are long).

I wondered if anyone had any thoughts on a way to fix this? I'd guess ghprb would need to get notified of the force push somehow via hook to cancel existing builds for a PR, but I'm not sure such a hook exists.

**Comment by mathroc** [comment]
I've not tried yet, but maybe this could help : http://blog.vincentpau.com/2012/08/02/cancel-obsolete-jenkins-queued-builds/

**Comment by MSch** [comment]
This actually works for us, you just have to add the `Cancel build on update` Trigger to the GH PR Builder configuration:

![2016-04-26 at 00 05](https://cloud.githubusercontent.com/assets/7475/14800563/b754df52-0b42-11e6-8500-bdff7fc22817.png)

**Comment by mathroc** [comment]
thx @MSch this works great! I don't know if it was recently added or if I missed it before but I think this issue can be closed. 

@jasonmadigan can you confirm it works for you too ?

**Comment by jasonmadigan** [comment]
@MSch @mathroc excellent, I didn't know this existed!
