### ISSUE TITLE
Status of PR are not updated when build manually

### ISSUE THREAD

**Issue by vankhoa011** [janinko/ghprb#393]
Hello,

I'm facing with a problem . Something other service failed,  so they made a failed PR test case. 

So I want to re-run test case. So I built manually by Build Job with parameter.

The Job was run successfully. However, the status of PR on Github didn't change. 

Any problem with that ?

**Comment by milliams** [comment]
I am seeing the same issue. It also makes it impossible to set the status of arbitrary branches with this plugin.

**Comment by mazimkhan** [comment]
I have the same issue. I can't use the automatically triggered build to test all valid permutations. So I fork out other GHPRB jobs via the automatic one. I guess Jenkins takes that as a manual trigger and PR status is not updated.

Any work on this recently?

**Comment by mazimkhan** [comment]
@janinko Can you please comment

**Comment by DavidTanner** [comment]
This plugin is meant to be the trigger of a build, not a part of it.  There are other plugins that will let you set the status of a commit from jenkins.
