### ISSUE TITLE
How to make ghprb work with manually triggered job?

### ISSUE THREAD

**Issue by dutor** [janinko/ghprb#491]
I set the `Branch Specifier` to `${sha1}` and it works well with PR. But when I manually triggered the job, the job failed since `${sha1}` was empty.

What I expect is that, when I manually start the job, it runs against a default branch, e.g. `origin/master`. I have tried to set the branch specifier to something like `${sha1:-origin/master}`, but it still did not work.

So, what should I do?

Thanks!

**Comment by dutor** [comment]
@DavidTanner Could you help me on this? Thanks !

**Comment by DavidTanner** [comment]
You would need to add the variables you want to use as job parameters and set them manually. If you build manually, then no other triggers are run, and GHPRB is just another trigger.

**Comment by dutor** [comment]
Very much appreciated. I added a string parameter `sha1` with a default value `master`, it works.
