### ISSUE TITLE
Not Triggered, Manual Build Fails Too (No Candidate Revisions)

### ISSUE THREAD

**Issue by jamescmartinez** [janinko/ghprb#5]
Hey there!

Just installed and configured as the readme says and I'm running into an issue: it won't pull. 

From Jenkins: 
`Fetching upstream changes from git@github.com:Tout/pullrequest-jenkins-test.git`
`No candidate revisions`
`ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.`
`Finished: FAILURE`

Inside of the repository, the model is git flow, so the pull request is being held on the `feature/edit_test` branch. The pull request is open but if I try to manually build from within Jenkins the build fails. Also, it is not hooking whenever a new pull request is opened, but I feel that might be another ticket.

Thoughts?

**Comment by dinhnhat0401** [comment]
@guimonz: You saved my day. Lol, just clone the project and every think work like a charm.
