### ISSUE TITLE
Support [ci-skip] flag

### ISSUE THREAD

**Issue by p0deje** [janinko/ghprb#60]
Something like Travis CI [supports](http://about.travis-ci.org/docs/user/how-to-skip-a-build/). You can add `[ci skip]` to commit message and build will not be triggered for this commit.

P.S. Thanks for awesome plugin!

**Comment by shehzan10** [comment]
I've been trying to get [skip ci] to make GHPRB skip the PR. However, I am yet to see a build get skipped. I have tried putting this phrase in the PR description (with other text) and in the comments but neither seem to work. What is the best place to put this phrase? Is there a PR I can see that used this feature?

**Comment by DavidTanner** [comment]
The default regex is .*\[skip\W+ci\].*, so if it has't been changed in your config then if you add [skip ci] anywhere in your comments the plugin will ignore it.  Check your config and verify it what the actual regex is though in the job config page under advanced.

**Comment by shehzan10** [comment]
.*\[skip\W+ci\].* is what I have (the default one) both in the main config as well as the job config. Unfortunately this doesn't seem to work. I've tried putting it in the merge header as well without success. I'll try poking around to see if I see any problems elsewhere.

**Comment by DavidTanner** [comment]
Looking at the code, the plugin will only skip the build if the comment is in the main PR comments
https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.22.4/src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java#L115

**Comment by shehzan10** [comment]
Thanks for that. I'll try it out.
