### ISSUE TITLE
Invalid refspec

### ISSUE THREAD

**Issue by jamescmartinez** [janinko/ghprb#7]
I'm getting an invalid refspec error when Jenkins tries to clone the repository.

`$ git clone --progress -o +refs/pull/*:refs/remotes/origin/pr/* git@github.com:MY_REPO_HERE`
`Cloning into 'MY_REPO_DIRECTORY_HERE'...`
`fatal: Invalid refspec '+refs/heads/*:refs/remotes/+refs/pull/*:refs/remotes/origin/pr/*/*'`

**Comment by sakthikanth** [comment]
If this command (" git pull origin https://github.com.... ") would cause result like this
Correct it to  (" git pull https://github.com.... ")

**Comment by foreverhermit** [comment]
kto ewe s red os?
