### ISSUE TITLE
Jenkins doesn't build branches when refspec has been defined

### ISSUE THREAD

**Issue by deiga** [janinko/ghprb#77]
I have defined `+refs/pull/*:refs/remotes/origin/pr/*` as my refspec and `${sha1}` as my branch to build.

Now this stops me from building my normal branches when something is pushed to them, how can this be fixed?

I tried setting multiple refspecs but it didn't seem to work, maybe my syntax was wrong...

**Comment by emmanuelmathot** [comment]
same issue for me, can someone help?

**Comment by KarelCemus** [comment]
I confirm this

**Comment by emmanuelmathot** [comment]
could you reopen that issue since it seems to be still a problem?

**Comment by DavidTanner** [comment]
@emmanuelmathot this is an issue with the Jenkins git plugin, unless the commit sha is incorrect that is provided from the ghprb plugin

**Comment by nullify005** [comment]
I usually wouldn't post of a clearly old thread, however I too can't get both PR & push to build using a single ref spec `+refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/*`

In the github hook log I see that the pushed branch doesn't get matched against for some reason
`Ignoring refs/heads/master as it doesn't match configured refspecs`

I did manage to get it working though, by specifying a refspec of `+refs/pull/*:refs/remotes/origin/pr/*` for one git repo & then adding a second identical git repo with an empty path spec

With the above it seems that both PR's & branches build properly

**Comment by Zoltu** [comment]
The steps provided by @nullify005 work for getting the job to trigger, but the job immediately fails on PR builds with
```
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
```

```
 > git -c core.askpass=true fetch --tags --progress git@domain.com:owner/repo.git +refs/heads/master:refs/remotes/origin/master
 > git rev-parse refs/remotes/origin/pr/2/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/2/merge^{commit} # timeout=10
 > git rev-parse origin/pr/2/merge^{commit} # timeout=10
```
Notice that it is (as expected) asking for only the master refs but then trying to find the PR refs (which won't exist locally).  This is using the Multiple SCM widget in the job configuration.

**Comment by Zoltu** [comment]
I was able to work around this by specifying both ref specs in both git jobs, but in reverse of each other:

One of them has:
```
+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/master:refs/remotes/origin/master
```

The other has:
```
+refs/heads/master:refs/remotes/origin/master +refs/pull/*:refs/remotes/origin/pr/*
```

From git's point of view, both are identical (since it doesn't care about order).  From the trigger's point of view, they are different because it appears to ignore all but the last.

**Comment by Zoltu** [comment]
Nevermind, it only works for the PR build when I do that, not the master build.  :/

**Comment by ssbarnea** [comment]
To be clear, does this means that currently it is impossible to build both master and PR inside the same jenkins job? If not impossible, what would be the correct way to do it?

**Comment by Zoltu** [comment]
@ssbarnea It is possible, though awkward.

![image](https://cloud.githubusercontent.com/assets/886059/13754655/b58f8a4a-ea0f-11e5-9fbe-3f25363f2778.png)

I also have triggers setup for `Build when a change is pushed to GitHub` and `GitHub Pull Request Builder`.  Along with that you will need to have your GitHub webhooks setup, just like you would if you had two separate jobs.

**Comment by hmgauthami** [comment]
HI, 
I am trying to build a PR from jenkins, Where it works as expected on master branch.
But I am trying to build same PR using different branch "abc". 

Kindly please help me how can i configure PR for "abc" branch. 

Thanks,
Gauthami

**Comment by Puneeth-n** [comment]
@Zoltu This doesn't seem to work.


I have a jenkins job that runs when code is pushed to `master` and `develop` branch. This job also picks up PRs. This job also has `sha1` as a build parameter to trigger builds manually.

The job picks up PRs and builds them. Same with pushes to `master` or `develop`. The issue is when The job is triggered manually. It seems to pickup a random branch. sometimes a PR, sometimes `origin/develop`.

**Job config**
````
build parameters: sha1 (default value: origin/<branchName>)
Branches to build: origin/master
Branches to build: origin/develop
Branches to build: origin/${sha1}
- [√ ]  Build when a change is pushed to GitHub
- [√ ]  GitHub Pull Request Builder
````

**Jenkins and plugin versions**
````
jenkins version: 2.7.1
	
Git client plugin: 2.0.0	
Git plugin: 3.0.0
GitHub API Plugin: 1.77	
GitHub plugin: 1.21.1
GitHub Pull Request Builder: 1.33.1
````

**Comment by itdependsnetworks** [comment]
To save others from mistyping like I did, it is: 

`+refs/heads/master:refs/remotes/origin/master` and
`+refs/pull/*:refs/remotes/origin/pr/*`

I also had to set branch specifier to `${GITHUB_PR_HEAD_SHA}` not `${sha1}` and unset `Lightweight checkout`

**Comment by vedrusss** [comment]
> HI,
> I am trying to build a PR from jenkins, Where it works as expected on master branch.
> But I am trying to build same PR using different branch "abc".
> 
> Kindly please help me how can i configure PR for "abc" branch.
> 
> Thanks,
> Gauthami

What you must do within section 'Repositories':
1) specify Repository URL (and credentials if required) - this you have already done;
2) click onto 'Advanced' and within appeared 'Refspec' field provide command "+refs/heads/branch_abc:refs/remotes/origin/branch_abc" - this will fetch remote branch into jenkins workspace;
3) within field 'Branch Specifier (blank for 'any')' input command "refs/heads/branch_abc" - this tells jenkins to build the project from branch "branch_abc".
